// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnWsXM53wInWiy9VlJ8hXhYkqoFHabOE',
    appId: '1:346983879482:android:d0001ab8997fa464bf7603',
    messagingSenderId: '346983879482',
    projectId: 'loanmanager-4eb16',
    storageBucket: 'loanmanager-4eb16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACWR8r4lij96s4wt7OEWRhf2MLhzMptwg',
    appId: '1:346983879482:ios:9e9da867495122d4bf7603',
    messagingSenderId: '346983879482',
    projectId: 'loanmanager-4eb16',
    storageBucket: 'loanmanager-4eb16.appspot.com',
    iosBundleId: 'com.example.moneymanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9dvrzFcDwHsqqAk74iTveiv5RByWhyHQ',
    appId: '1:346983879482:web:4b24e61f7f19a90cbf7603',
    messagingSenderId: '346983879482',
    projectId: 'loanmanager-4eb16',
    authDomain: 'loanmanager-4eb16.firebaseapp.com',
    storageBucket: 'loanmanager-4eb16.appspot.com',
  );
}
